// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: '1:444623396920:ios:1c80a6fbf1058a9f82c6cd',
    messagingSenderId: '444623396920',
    projectId: 'chaincare-a6ef7',
    storageBucket: 'chaincare-a6ef7.firebasestorage.app',
    iosBundleId: 'com.example.chaincare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: '1:444623396920:ios:1c80a6fbf1058a9f82c6cd',
    messagingSenderId: '444623396920',
    projectId: 'chaincare-a6ef7',
    storageBucket: 'chaincare-a6ef7.firebasestorage.app',
    iosBundleId: 'com.example.chaincare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: '1:444623396920:web:b73d54515902a9a182c6cd',
    messagingSenderId: '444623396920',
    projectId: 'chaincare-a6ef7',
    authDomain: 'chaincare-a6ef7.firebaseapp.com',
    storageBucket: 'chaincare-a6ef7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: '1:444623396920:web:b73d54515902a9a182c6cd',
    messagingSenderId: '444623396920',
    projectId: 'chaincare-a6ef7',
    authDomain: 'chaincare-a6ef7.firebaseapp.com',
    storageBucket: 'chaincare-a6ef7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: '1:444623396920:android:018909f2ef5663c882c6cd',
    messagingSenderId: '444623396920',
    projectId: 'chaincare-a6ef7',
    storageBucket: 'chaincare-a6ef7.firebasestorage.app',
  );

}